### ISSUE TITLE
copyDefaults

### ISSUE THREAD

**Issue by PeRaDi** [corycaron5/Multiple-Configuration-Manager#1]
How do I copy defaults on my cfgs?

**Comment by corycaron5** [comment]
> How do I copy defaults on my cfgs?

Hello,

Before I explain how to copy defaults to your config, I would suggest using the ConfigUtility that I created: https://github.com/corycaron5/ConfigUtility
It has many more functions, has improved efficiency, and should be easier to use.
This version of the application is outdated and should no longer be used, however the instructions below apply to the ConfigUtility as well.

Copying defaults to one of these configs would be the same as normal with the Bukkit API. 
A FileConfiguration object is returned after creating or getting the config, we would then need to set the defaults and copy them:
`config.addDefault("path", "value");
config.options().copyDefaults(true);
configManager.saveConfig(config, "name", "directory");`

**Comment by PeRaDi** [comment]
Sorry for asking again but, what is the the config parameter at the line `configManager.saveConfig(config, "name", "directory");`
I'm trying to run the plugin with next code, but it gives me a NullPointerException: 
`cfgM.createConfig("config", this);`
`cfgM.createConfig("lang", this);`
`cfgM.getConfig("config", this).addDefault(this.getDataFolder().getPath(), true);`
`cfgM.getConfig("lang", this).addDefault(this.getDataFolder().getPath(), true);`
`cfgM.saveConfig(cfgM.getConfig("config", this), "config", this.getDataFolder().getPath());`
`cfgM.saveConfig(cfgM.getConfig("lang", this), "lang", this.getDataFolder().getPath());`

**Comment by corycaron5** [comment]
The config parameter is the FileConfiguration object that is returned when using `createConfig()`
So the code would look something like this:
`FileConfiguration config = cfgM.createConfig("name", this);`
`config.addDefault("key", "value");`
`config.options().copyDefaults(true);`
`cfgM.saveConfig(config, "name", this)`

Java is object oriented, therefore every method will either be void, or return a value of some sort.
Using the getConfig() method repeatedly wont work, and even if it did, you would be killing the efficiency of the code because the slowest part of any program is the reading/writing to a drive.
What were doing in the above code is creating a FileConfiguration object from scratch, then adding information to it, and then saving it to the disk.

Also, I would again suggest switching to the ConfigUtility that I linked above because it is more efficient and advanced.
